//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KrahmerSoft.MediaTesterGui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KrahmerSoft.MediaTesterGui.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while testing..
        /// </summary>
        internal static string AnExceptionOccurredWhileTesting {
            get {
                return ResourceManager.GetString("AnExceptionOccurredWhileTesting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average read speed.
        /// </summary>
        internal static string AverageReadSpeed {
            get {
                return ResourceManager.GetString("AverageReadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average write speed.
        /// </summary>
        internal static string AverageWriteSpeed {
            get {
                return ResourceManager.GetString("AverageWriteSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice: Be sure to delete the temporary directory before using the media..
        /// </summary>
        internal static string BeSureToDeleteTemporaryDirectory {
            get {
                return ResourceManager.GetString("BeSureToDeleteTemporaryDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ButtonNo {
            get {
                return ResourceManager.GetString("ButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOk {
            get {
                return ResourceManager.GetString("ButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ButtonYes {
            get {
                return ResourceManager.GetString("ButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string Bytes {
            get {
                return ResourceManager.GetString("Bytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes/sec.
        /// </summary>
        internal static string BytesPerSecond {
            get {
                return ResourceManager.GetString("BytesPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required to change language.
        /// </summary>
        internal static string ChangeLanguageRestart {
            get {
                return ResourceManager.GetString("ChangeLanguageRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application must restart to change the language.
        ///Any unsaved settings will be lost.
        ///Would you like to continue?.
        /// </summary>
        internal static string ChangeLanguageRestartDetails {
            get {
                return ResourceManager.GetString("ChangeLanguageRestartDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check device and folder permissions or reconnect the drive and retry..
        /// </summary>
        internal static string CheckDeviceAndFolderPermissions {
            get {
                return ResourceManager.GetString("CheckDeviceAndFolderPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaTester works best if the target media is empty.
        ///Continue with non-destructive test?.
        /// </summary>
        internal static string ContinueWithTest {
            get {
                return ResourceManager.GetString("ContinueWithTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Loading Options.
        /// </summary>
        internal static string ErrorLoadingOptions {
            get {
                return ResourceManager.GetString("ErrorLoadingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading options config file.
        ///Continuing with defaults..
        /// </summary>
        internal static string ErrorLoadingOptionsDetails {
            get {
                return ResourceManager.GetString("ErrorLoadingOptionsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while removing temporary data file..
        /// </summary>
        internal static string ExceptionWhileRemovingTempFiles {
            get {
                return ResourceManager.GetString("ExceptionWhileRemovingTempFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAIL.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED block {AbsoluteDataBlockIndex}! Byte index: {AbsoluteDataByteIndex}.
        /// </summary>
        internal static string FailedBlockByteIndex {
            get {
                return ResourceManager.GetString("FailedBlockByteIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAILED writing block {AbsoluteDataBlockIndex}. Byte index: {AbsoluteDataByteIndex}..
        /// </summary>
        internal static string FailedWritingBlock {
            get {
                return ResourceManager.GetString("FailedWritingBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying first failing byte....
        /// </summary>
        internal static string IdentifyingFirstFailingByte {
            get {
                return ResourceManager.GetString("IdentifyingFirstFailingByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Language.
        /// </summary>
        internal static string InvalidLanguage {
            get {
                return ResourceManager.GetString("InvalidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured language name ({InvalidLanguageName}) is invalid.
        ///The system default will be used: {DefaultLanguageName}.
        /// </summary>
        internal static string InvalidLanguageDetails {
            get {
                return ResourceManager.GetString("InvalidLanguageDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid target.
        /// </summary>
        internal static string InvalidTarget {
            get {
                return ResourceManager.GetString("InvalidTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media test FAILED! First failing byte: {FirstFailingByteIndex}. Verified {TotalBytesVerified} Bytes..
        /// </summary>
        internal static string MediaTestFailed {
            get {
                return ResourceManager.GetString("MediaTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media test PASSED!.
        /// </summary>
        internal static string MediaTestPassed {
            get {
                return ResourceManager.GetString("MediaTestPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free space to write test results file.
        /// </summary>
        internal static string NotEnoughFreeSpaceToWrite {
            get {
                return ResourceManager.GetString("NotEnoughFreeSpaceToWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASS.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick test.
        /// </summary>
        internal static string QuickTest {
            get {
                return ResourceManager.GetString("QuickTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {FilesDeleted} temp data file..
        /// </summary>
        internal static string RemovedTempDataFile {
            get {
                return ResourceManager.GetString("RemovedTempDataFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed {FilesDeleted} temp data files..
        /// </summary>
        internal static string RemovedTempDataFiles {
            get {
                return ResourceManager.GetString("RemovedTempDataFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing temp data files....
        /// </summary>
        internal static string RemovingTempDataFiles {
            get {
                return ResourceManager.GetString("RemovingTempDataFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MediaTesterResults_{DateTime}_{PassFail}.txt.
        /// </summary>
        internal static string ResultsFilename {
            get {
                return ResourceManager.GetString("ResultsFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start test?.
        /// </summary>
        internal static string StartTest {
            get {
                return ResourceManager.GetString("StartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        internal static string SystemDefault {
            get {
                return ResourceManager.GetString("SystemDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary data path.
        /// </summary>
        internal static string TemporaryDataPath {
            get {
                return ResourceManager.GetString("TemporaryDataPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected target is invalid or does not exist!.
        /// </summary>
        internal static string TheSelectedTargetIsInvalid {
            get {
                return ResourceManager.GetString("TheSelectedTargetIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The test was aborted by the user..
        /// </summary>
        internal static string TheTestWasAborted {
            get {
                return ResourceManager.GetString("TheTestWasAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total reported available space.
        /// </summary>
        internal static string TotalReportedAvailableSpace {
            get {
                return ResourceManager.GetString("TotalReportedAvailableSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total reported media size.
        /// </summary>
        internal static string TotalReportedMediaSize {
            get {
                return ResourceManager.GetString("TotalReportedMediaSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified block {AbsoluteDataBlockIndex}. Byte index: {AbsoluteDataByteIndex}.
        /// </summary>
        internal static string VerifiedBlockByteIndex {
            get {
                return ResourceManager.GetString("VerifiedBlockByteIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified {TotalBytesVerified} Bytes of {TargetTotalBytes} Bytes total..
        /// </summary>
        internal static string VerifiedXBytesOfXTotal {
            get {
                return ResourceManager.GetString("VerifiedXBytesOfXTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write.
        /// </summary>
        internal static string Write {
            get {
                return ResourceManager.GetString("Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrote test results file.
        /// </summary>
        internal static string WroteTestResultsFile {
            get {
                return ResourceManager.GetString("WroteTestResultsFile", resourceCulture);
            }
        }
    }
}
